fix: stop 'git-track-repos update' from being ran as a pre-hook when the operation is 'track-repos'

diff --git a/git-shim b/git-shim
--- a/git-shim
+++ b/git-shim
@@ -16,11 +16,11 @@ function pre_hooks() {
   local operation="$1"
   case "${operation}" in
 
+    'clone'|'track-repos')
+      # Do nothing - this stops us from hitting the default case for these particular operations
+      ;;
     *) 
-      # TODO: figure out how best have exclusions
-      if [[ "${operation}" != 'clone' ]]; then
-        git-track-repos --quiet update
-      fi
+      git-track-repos --quiet update || true # Ok to fail (not called in)
       ;;
 
   esac
